### PR TITLE
Issac to yolo

### PR DESCRIPTION
**Pull request by MinhxNguyen7**
Write the description @Dat-Bois. What's done, what's not?

### CODE REVIEW

**Comment by Dat-Bois** [comment]
View README.md 

But in essence, it's able to create a Yolo dataset from a single folder with all the issac datagen and tile the images as needed.

**Review by EricPedley — CHANGES_REQUESTED** [review]
What are the testFiles and testImages directories for? Are those left over from you playing around with stuff to get this working, or are they supposed to remain in the repo? Other than that, looks good enough. Nobody's gonna die if we merge this in and it has a bug, we'll just fix it later.

**Comment by Dat-Bois** [comment]
Si they are standalone to ensure that some independent functionality works. I want to leave them in for future reference in case something needs to be debugged/fixed. They arent explicitly needed though.

**Review by EricPedley — APPROVED** [review]
k

**Pull request merged**
